# Book settings
title: "06-643: Creating Scientific Software with AI Coding Agents"
author: Prof. John Kitchin
copyright: "2026"
logo: logo.png

# Force re-execution of notebooks on each build
execute:
  execute_notebooks: "off"

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jkitchin/s26-06643
  path_to_book: sse
  branch: main

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  home_page_in_navbar: false

launch_buttons:
  notebook_interface: "classic"
  colab_url: "https://colab.research.google.com"

sphinx:
  config:
    html_show_copyright: true
    suppress_warnings: ["mystnb.unknown_mime_type"]
